# Generated by Django 5.2.12 on 2026-03-06 20:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(help_text='Name of the supplier', max_length=255)),
                ('reference_no', models.CharField(blank=True, db_index=True, help_text='Optional unique reference (e.g. PO number)', max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed')], db_index=True, default='DRAFT', help_text='Purchase status: DRAFT or CONFIRMED', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total cost computed from items', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this purchase', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity ordered (must be > 0)', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit (must be >= 0)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.ForeignKey(help_text='Product being purchased', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='catalog.product')),
                ('purchase', models.ForeignKey(help_text='Purchase this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchase')),
            ],
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['status'], name='purchases_p_status_0434fa_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['reference_no'], name='purchases_p_referen_1be307_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['created_by', '-created_at'], name='purchases_p_created_1e1b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['purchase'], name='purchases_p_purchas_ec4548_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['product'], name='purchases_p_product_52a9a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseitem',
            unique_together={('purchase', 'product')},
        ),
    ]
