# Generated by Django 5.2.12 on 2026-03-05 21:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Current stock quantity (must be >= 0)', validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(help_text='One-to-one relationship with Product', on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.product')),
            ],
            options={
                'verbose_name_plural': 'Stock',
                'indexes': [models.Index(fields=['quantity'], name='inventory_s_quantit_287c3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In (Purchase/Receive)'), ('OUT', 'Stock Out (Sale/Transfer)'), ('ADJUSTMENT', 'Inventory Adjustment')], help_text='Type of stock movement', max_length=20)),
                ('quantity', models.IntegerField(help_text='Quantity moved (must be positive)', validators=[django.core.validators.MinValueValidator(1)])),
                ('reference', models.CharField(blank=True, db_index=True, help_text='Optional reference (PO/SO/etc)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this movement', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this movement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Product affected by this movement', on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='inventory_s_product_cfb4fb_idx'), models.Index(fields=['movement_type', '-created_at'], name='inventory_s_movemen_a71f62_idx'), models.Index(fields=['reference'], name='inventory_s_referen_16defd_idx')],
            },
        ),
    ]
