# Generated by Django 5.2.12 on 2026-03-04 21:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Category name (must be unique)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional category description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='catalog_cat_name_39f70b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Product name', max_length=255)),
                ('sku', models.CharField(db_index=True, help_text='Unique stock-keeping unit', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional product description', null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit (must be >= 0)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_level', models.IntegerField(default=0, help_text='Minimum stock level before reorder (default 0)', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether product is available for purchase/sale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional category for this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['sku'], name='catalog_pro_sku_2c4c34_idx'), models.Index(fields=['name'], name='catalog_pro_name_f603c0_idx'), models.Index(fields=['is_active'], name='catalog_pro_is_acti_14fc6b_idx'), models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_891fe8_idx')],
            },
        ),
    ]
